apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-db-secret
  namespace: production
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore

  target:
    name: backend-db-secret
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: eks-3tier-prod/database
