{{- if .Values.backend.rollout.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: backend-canary
  labels:
    app: backend-canary
    {{- include "eks-3-tier-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type | default "ClusterIP" }}
  selector:
    app: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port | default 8080 }}
      targetPort: {{ .Values.backend.service.port | default 8080 }}
{{- end }}
