{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "eks-3-tier-app.fullname" . }}-migration
  labels:
    app: backend-migration
    {{- include "eks-3-tier-app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.migration.backoffLimit | default 3 }}
  ttlSecondsAfterFinished: {{ .Values.migration.ttlSecondsAfterFinished | default 86400 }}
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: db-migrate
          image: "{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.migration.image.pullPolicy | default "Always" }}
          command: ["./migrate"]
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: DB_NAME
            - name: DB_SSLMODE
              {{- if .Values.postgres.enabled }}
              value: {{ .Values.postgres.db.sslMode | default "disable" | quote }}
              {{- else }}
              value: "require"
              {{- end }}
{{- end }}
