{{- if and .Values.postgres.enabled .Values.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: postgres
    {{- include "eks-3-tier-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.postgres.persistence.accessMode }}
  storageClassName: {{ .Values.postgres.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
{{- end }}
