{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: postgres
    {{- include "eks-3-tier-app.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
  selector:
    app: postgres
  type: {{ .Values.postgres.service.type }}
{{- end }}
