{{- if .Values.databaseSecret.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.databaseSecret.externalSecrets.secretStoreName }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.databaseSecret.externalSecrets.region }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-db-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.databaseSecret.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: backend-db-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.databaseSecret.externalSecrets.secretKey }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: backend-db-secret
  labels:
    {{- include "eks-3-tier-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $dbHost := .Values.databaseSecret.secretData.dbHost }}
  {{- $dbPort := .Values.databaseSecret.secretData.dbPort }}
  {{- $dbUser := .Values.databaseSecret.secretData.dbUsername }}
  {{- $dbPass := .Values.databaseSecret.secretData.dbPassword }}
  {{- $dbName := .Values.databaseSecret.secretData.dbName }}
  {{- if .Values.postgres.enabled }}
    {{- $dbHost = "db" }}
    {{- $dbPort = .Values.postgres.service.port | toString }}
    {{- $dbUser = .Values.postgres.db.user }}
    {{- $dbPass = .Values.postgres.db.password }}
    {{- $dbName = .Values.postgres.db.name }}
  {{- end }}
  DB_HOST: {{ default "db" $dbHost | b64enc | quote }}
  DB_PORT: {{ default "5432" $dbPort | b64enc | quote }}
  DB_USERNAME: {{ default "postgres" $dbUser | b64enc | quote }}
  DB_PASSWORD: {{ default "postgres_password" $dbPass | b64enc | quote }}
  DB_NAME: {{ default "tasks_db" $dbName | b64enc | quote }}
{{- end }}
